language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer require php-coveralls/php-coveralls
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
